org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.19.5
fabric_version=0.116.17+1.21.1

mod_version=0.1.10
maven_group=com.cobblelore
archives_base_name=cobblelore-legendary

# CobbleLore/cobblelore pack/pack.json (0.1.149)
cobblemon_version=gBW3vLC7
myths_version=eg83qtSQ
legendary_monuments_version=F6Ub0Gga
